version: '3.8'

services:
  web:
    build: .
    command: gunicorn AITS_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=AITS_project.settings
      - SECRET_KEY='django-insecure--8rf042$od@rh!f)kn1=awqj2((x=qw%k#(c-9$&2ix9d4xh*z'
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3

  # Uncomment if you need PostgreSQL locally:
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=mydb
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data: