services:
  - type: web
    name: aits-backend
    env: python
    plan: free  # (free plan unless you upgrade later)
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn AITS_project.wsgi:application
